### PR TITLE
new so for 32 bit arm with php 7.4

### PR DESCRIPTION
**Pull request by tim-moody**
Magic numbers are:

PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902

### CODE REVIEW

**Comment by holta** [comment]
Many thanks @tim-moody (is there any reason not to merge this?)

Background for others:

- https://github.com/iiab/php-stem/blob/main/README.md
- https://github.com/iiab/iiab/blob/master/roles/www_base/tasks/php-stem.yml
- https://github.com/iiab/iiab/issues/2864

**Comment by tim-moody** [comment]
it built but I haven't actually tested it

**Comment by holta** [comment]
> Magic numbers are:
> 
> PHP Api Version: 20190902

> Zend Module Api No: 20190902
> Zend Extension Api No: 320190902

Can the 2 Zend lines...be ignored...as a practical matter...when integrating `stem-armhf-7.4.so` into IIAB?

**Comment by tim-moody** [comment]
I assume so. This is just what the build spit out, but I expect 20190902 is the relevant number.

**Comment by holta** [comment]
I'm merging this to broaden testing.  Thanks everyone who helped.

**Comment by holta** [comment]
Testing unfortunately did NOT work, as seen at http://10.8.0.14/modules/es-wikihow/content/Portada.html here:

image

In contrast, the same 12.6GB [es-wikihow](http://iiab.me/modules/es-wikihow/) content DOES work here:

image

@tim-moody we should try to diagnose this in coming days when you hopefully have time?  Do you see any immediate problems on 10.8.0.14 below?

```
root@box:~# ls -l /usr/lib/php/20190902/stem.so
-rw-r--r-- 1 root root 568504 Dec 25 10:32 /usr/lib/php/20190902/stem.so

root@box:~# ls -l /etc/php/7.4/mods-available/stem.ini
-rw-r--r-- 1 root root 70 Dec 25 11:28 /etc/php/7.4/mods-available/stem.ini

root@box:~# ls -l /etc/php/7.4/fpm/conf.d/20-stem.ini
lrwxrwxrwx 1 root root 36 Dec 25 10:44 /etc/php/7.4/fpm/conf.d/20-stem.ini -> /etc/php/7.4/mods-available/stem.ini

root@box:~# cat /etc/php/7.4/mods-available/stem.ini
; configuration for php common module
; priority=20
extension=stem.so
```

Somewhat Related:

- PR iiab/iiab#3080

**Comment by tim-moody** [comment]
I did systemctl restart php7.4-fpm.service and think it works

**Comment by holta** [comment]
> I did systemctl restart php7.4-fpm.service and think it works

Incredible news, Thanks!

Strangely on a different Raspberry Pi 4, that is instead using [local_vars_medical.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_medical.yml), searching es-wikihow does not work.

Specifically, both aspects of search do not work: (1) search term suggestions (as you type into the search textfield), and (2) search results themselves...both do not work here:

- http://10.8.0.50/modules/es-wikihow/content/Portada.html
- http://10.8.0.50/modules/es-wikihow/content/search/search.php?query=escuela&sa=Buscar 

Even after I...

1) Rebooted the Raspberry Pi 4 = 10.8.0.50 =182-rpi4-lite-MEDICAL-PR3080.
2) Ran `systemctl restart php7.4-fpm.service`
3) Ran `./runrole www_options` for good measure.

Any suggestions...as to what I/we should try on 10.8.0.50 ?

(FYI the stem files are in place, just as on 10.8.0.14, as confirmed by...)

```
root@box:~# ls -l /usr/lib/php/20190902/stem.so
-rw-r--r-- 1 root root 568504 Dec 25 13:17 /usr/lib/php/20190902/stem.so

root@box:~# ls -l /etc/php/7.4/mods-available/stem.ini
-rw-r--r-- 1 root root 70 Dec 25 13:17 /etc/php/7.4/mods-available/stem.ini

root@box:~# ls -l /etc/php/7.4/fpm/conf.d/20-stem.ini
lrwxrwxrwx 1 root root 36 Dec 25 13:17 /etc/php/7.4/fpm/conf.d/20-stem.ini -> /etc/php/7.4/mods-available/stem.ini

root@box:~# cat /etc/php/7.4/mods-available/stem.ini
; configuration for php common module
; priority=20
extension=stem.so
```

**Comment by holta** [comment]
I'm still baffled by the [above failure](https://github.com/iiab/php-stem/pull/3#issuecomment-1001070050) of 10.8.0.50 to [search es-wikihow](http://10.8.0.50/modules/es-wikihow/content/search/search.php?query=escuela&sa=Buscar) (is this really due to [local_vars_medical.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_medical.yml) ??)
I hope we can solve it eventually.  Does anybody have ideas to diagnose this?

Meantime the good news is: 2 out of 3 RPi 4 installs worked perfectly with es-wikihhow.
(FWIW, both are based on [local_vars_small.yml](https://github.com/iiab/iiab/blob/master/vars/local_vars_small.yml))

**Comment by tim-moody** [comment]
log on .50 says

Uncaught Error: Class 'SQLite3' not found in /library/www/html/modules/es-wikihow/content/search/suggest.php:4

**Comment by holta** [comment]
> log on .50 says
> 
> Uncaught Error: Class 'SQLite3' not found in /library/www/html/modules/es-wikihow/content/search/suggest.php:4

Thanks.  That helps reconfirm the fix I applied last night:

- PR iiab/iiab#3082

**Pull request merged**
